# Generated by Django 3.2.7 on 2021-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Прошел активацию?'),
        ),
    ]
