# Generated by Django 3.2.7 on 2021-09-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ident', '0002_auto_20210919_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Владелец системы', max_length=64, unique=True, verbose_name='Наименование организации'),
        ),
    ]
