# Generated by Django 3.2.7 on 2021-09-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ident', '0003_alter_organization_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
