# Generated by Django 3.2.7 on 2021-09-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование проекта')),
                ('repo', models.URLField(blank=True, verbose_name='Ссылка на репозиторий')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'managed': False,
            },
        ),
    ]
