# Generated by Django 3.2.7 on 2021-09-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptd', '0002_auto_20210922_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='authors',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='users',
            new_name='user',
        ),
    ]
